# Generated by Django 5.2.3 on 2025-06-29 01:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leadExtraction',
            fields=[
                ('leadid', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('funnel', models.TextField()),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('status', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('user_assgnee', models.TextField()),
            ],
        ),
    ]
