# Generated by Django 5.2.3 on 2025-06-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadextraction',
            name='leadid',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
