# Generated by Django 5.2.3 on 2025-06-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_extraction', '0002_alter_leadextraction_leadid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leadExtraction',
            new_name='Lead',
        ),
    ]
