# Generated by Django 5.2.3 on 2025-06-29 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_extraction', '0003_rename_leadextraction_to_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('funnelid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('funnel_name', models.CharField(max_length=1000)),
                ('leads_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stageid', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('stagename', models.CharField(max_length=1000)),
                ('leads_count', models.IntegerField()),
                ('expires_after', models.IntegerField()),
                ('order', models.IntegerField()),
                ('sum_value', models.FloatField()),
                ('funnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='leads_extraction.funnel')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.OneToOneField(default=uuid.UUID('9612ee4b-580f-4de0-ac5a-11f86ad69b95'), on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='leads_extraction.stage'),
            preserve_default=False,
        ),
    ]
