# Generated by Django 5.2.3 on 2025-06-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_extraction', '0004_funnel_stage_lead_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='leads_extraction.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='leads_extraction.funnel'),
        ),
    ]
