# Generated by Django 5.2.3 on 2025-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_extraction', '0005_alter_lead_stage_alter_stage_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.TextField(default='Logicomer'),
            preserve_default=False,
        ),
    ]
